name: snakemake_env
channels:
  - defaults
dependencies:
  - _libgcc_mutex=0.1=main
  - _openmp_mutex=5.1=1_gnu
  - ca-certificates=2024.7.2
  - ld_impl_linux-64=2.38
  - libffi=3.4.4
  - libgcc-ng=11.2.0
  - libgomp=11.2.0
  - libstdcxx-ng=11.2.0
  - ncurses=6.4
  - openssl=3.0.14
  - pip=24.0
  - python=3.11
  - readline=8.2
  - setuptools=69.5.1
  - sqlite=3.45.3
  - tk=8.6.14
  - wheel=0.43.0
  - xz=5.4.6
  - zlib=1.2.13
  - pip:
      - appdirs==1.4.4
      - attrs==23.2.0
      - certifi==2024.7.4
      - charset-normalizer==3.3.2
      - configargparse==1.7
      - connection-pool==0.0.3
      - datrie==0.8.2
      - docutils==0.20.1
      - dpath==2.2.0
      - fastjsonschema==2.20.0
      - gitdb==4.0.11
      - gitpython==3.1.43
      - humanfriendly==10.0
      - idna==3.7
      - importlib-resources==6.4.0
      - jinja2==3.1.4
      - jsonschema==4.23.0
      - jsonschema-specifications==2023.12.1
      - jupyter-core==5.7.2
      - markupsafe==2.1.5
      - nbformat==5.10.4
      - numpy==1.24.4
      - packaging==24.1
      - pandas==2.0.3
      - pkgutil-resolve-name==1.3.10
      - plac==1.4.3
      - platformdirs==4.2.2
      - psutil==6.0.0
      - pulp==2.7.0
      - python-dateutil==2.9.0.post0
      - pytz==2024.1
      - pyyaml==6.0.1
      - referencing==0.35.1
      - requests==2.32.3
      - reretry==0.11.8
      - rpds-py==0.19.0
      - six==1.16.0
      - smart-open==7.0.4
      - smmap==5.0.1
      - snakemake==7.32.4
      - stopit==1.1.2
      - tabulate==0.9.0
      - throttler==1.2.2
      - toposort==1.10
      - traitlets==5.14.3
      - tzdata==2024.1
      - urllib3==2.2.2
      - wrapt==1.16.0
      - yte==1.5.4
      - zipp==3.19.2
